/*[MenuItem("Tools/Update Item Types")]
private static void UpdateItemTypes()
{
	string enumName = "ItemType";
	string[] guids = AssetDatabase.FindAssets("", new string[] { "Assets/Prefabs/Items" });
	string[] enumEntries = new string[guids.Length];
	for (int i = 0; i < guids.Length; i++)
	{
		string[] split = AssetDatabase.GUIDToAssetPath(guids[i]).Split('/');
		enumEntries[i] = split[split.Length - 1].Replace(".prefab", "");
	}
	string filePathAndName = "Assets/Scripts/" + enumName + ".cs"; //The folder Scripts/Enums/ is expected to exist

	using (StreamWriter streamWriter = new StreamWriter(filePathAndName))
	{
		streamWriter.WriteLine("//This file is auto-generated by Tools > Update Item Types \n");
		streamWriter.WriteLine("public enum " + enumName);
		streamWriter.WriteLine("{");
		for (int i = 0; i < enumEntries.Length; i++)
		{
			streamWriter.WriteLine("\t" + enumEntries[i] + ",");
		}
		streamWriter.WriteLine("}");
	}
	AssetDatabase.Refresh();
}*/